import {
  Calculator,
  ArrowLeftRight,
  Coins,
  Sigma,
  Scale,
  Calendar,
  Cake,
  LayoutGrid,
  Percent,
  Divide,
  Receipt,
  Tag,
  Landmark,
  BadgePercent,
  TrendingUp,
  Wallet,
  BarChart3,
  Dices,
  History,
  Settings,
} from 'lucide-react';

export const CATEGORIES = [
  { id: 'CALCULATE', label: 'Calculate' },
  { id: 'CONVERTERS', label: 'Converters' },
  { id: 'SOLVE', label: 'Solve' },
  { id: 'FINANCE', label: 'Finance' },
  { id: 'HEALTH', label: 'Health' },
  { id: 'DATE_TIME', label: 'Date & Time' },
  { id: 'TOOLS', label: 'Tools' },
  { id: 'SYSTEM', label: 'System' },
];

export const TOOLS = [
  // Overview
  {
    id: 'dashboard',
    name: 'Dashboard',
    shortName: 'Home',
    icon: LayoutGrid,
    description: 'CalcX suite overview, favorites, and fast tool launcher',
    category: 'CALCULATE',
    color: '#6366f1',
    isNavOverview: true,
  },

  // CALCULATE
  {
    id: 'calculator',
    name: 'Smart Calculator',
    shortName: 'Calc',
    icon: Calculator,
    description: 'Natural expressions, Ans previous answer, scientific trig, logs, powers, and memory',
    category: 'CALCULATE',
    color: '#8b5cf6',
  },

  // CONVERTERS
  {
    id: 'unit',
    name: 'Unit Converter',
    shortName: 'Units',
    icon: ArrowLeftRight,
    description: '13 categories: length, weight, volume, temperature, speed, data, and more',
    category: 'CONVERTERS',
    color: '#0ea5e9',
  },
  {
    id: 'currency',
    name: 'Currency Converter',
    shortName: 'Currency',
    icon: Coins,
    description: 'Real-time exchange rates for 30+ global currencies with offline cache',
    category: 'CONVERTERS',
    color: '#10b981',
  },

  // SOLVE
  {
    id: 'equation',
    name: 'Equation Solver',
    shortName: 'Equations',
    icon: Sigma,
    description: 'Linear & quadratic polynomial solver with step-by-step mathematical reasoning',
    category: 'SOLVE',
    color: '#f59e0b',
  },
  {
    id: 'statistics',
    name: 'Statistics Calculator',
    shortName: 'Stats',
    icon: BarChart3,
    description: 'Mean, median, mode, range, variance, and standard deviation for datasets',
    category: 'SOLVE',
    color: '#3b82f6',
  },

  // FINANCE
  {
    id: 'emi',
    name: 'EMI / Loan Calculator',
    shortName: 'EMI',
    icon: Landmark,
    description: 'Monthly loan EMI, total interest, and complete month-by-month amortization schedule',
    category: 'FINANCE',
    color: '#10b981',
  },
  {
    id: 'interest',
    name: 'Interest Calculator',
    shortName: 'Interest',
    icon: TrendingUp,
    description: 'Simple Interest, Compound Interest, side-by-side comparison, and SIP investments',
    category: 'FINANCE',
    color: '#059669',
  },
  {
    id: 'gst',
    name: 'GST Calculator (India)',
    shortName: 'GST',
    icon: BadgePercent,
    description: 'Standard 5%, 12%, 18%, 28% GST with inclusive/exclusive modes and CGST+SGST split',
    category: 'FINANCE',
    color: '#f97316',
  },
  {
    id: 'salary',
    name: 'Salary / Income Calculator',
    shortName: 'Salary',
    icon: Wallet,
    description: 'Annual CTC to monthly gross, EPF, professional tax, and estimated net take-home',
    category: 'FINANCE',
    color: '#14b8a6',
  },
  {
    id: 'discount',
    name: 'Discount Calculator',
    shortName: 'Discount',
    icon: Tag,
    description: 'Calculate sale savings, net price after discount, and optional sales tax',
    category: 'FINANCE',
    color: '#e11d48',
  },
  {
    id: 'tip',
    name: 'Tip & Bill Splitter',
    shortName: 'Tip',
    icon: Receipt,
    description: 'Tip percentage calculator with bill split per person for dining and services',
    category: 'FINANCE',
    color: '#d97706',
  },

  // HEALTH
  {
    id: 'bmi',
    name: 'BMI Calculator',
    shortName: 'BMI',
    icon: Scale,
    description: 'Body Mass Index calculator with visual health scale, category, and ranges',
    category: 'HEALTH',
    color: '#ec4899',
  },

  // DATE & TIME
  {
    id: 'date',
    name: 'Date Calculator',
    shortName: 'Dates',
    icon: Calendar,
    description: 'Date differences, time offsets, and day-of-week leap year analysis',
    category: 'DATE_TIME',
    color: '#06b6d4',
  },
  {
    id: 'age',
    name: 'Age Calculator',
    shortName: 'Age',
    icon: Cake,
    description: 'Exact age in years, months, days, lifetime stats, and birthday countdown',
    category: 'DATE_TIME',
    color: '#a855f7',
  },

  // TOOLS
  {
    id: 'percentage',
    name: 'Percentage Calculator',
    shortName: 'Percent',
    icon: Percent,
    description: 'X% of Y, X as % of Y, percentage increase, and percentage decrease',
    category: 'TOOLS',
    color: '#6366f1',
  },
  {
    id: 'fraction',
    name: 'Fraction Calculator',
    shortName: 'Fraction',
    icon: Divide,
    description: 'Add, subtract, multiply, and divide fractions with automated GCD simplification',
    category: 'TOOLS',
    color: '#8b5cf6',
  },
  {
    id: 'random',
    name: 'Random Number Generator',
    shortName: 'Random',
    icon: Dices,
    description: 'Generate customizable ranges of random integers with unique selection toggle',
    category: 'TOOLS',
    color: '#ec4899',
  },

  // SYSTEM
  {
    id: 'history',
    name: 'Calculation History',
    shortName: 'History',
    icon: History,
    description: 'Unified cross-tool calculation history with reuse, copy, and search',
    category: 'SYSTEM',
    color: '#64748b',
  },
  {
    id: 'settings',
    name: 'Settings & About',
    shortName: 'Settings',
    icon: Settings,
    description: 'Themes, angle modes, currency formatting, and CalcX suite information',
    category: 'SYSTEM',
    color: '#475569',
  },
];
